version: "3.9"
services:
  power-app:
    build: .
    container_name: power-notify
    ports: ["3007:3000"]
    env_file: .env
    volumes:
      - ./prices.db:/app/prices.db
    restart: unless-stopped
