version: "3.9"

services:
  power-app:
    build: .
    container_name: power-notify
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./prices.db:/app/prices.db
    restart: unless-stopped
